# -*- coding: utf-8 -*-
"""json_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSAlZzCTZLrzYGjGNsBRTnIsWIM5BNjI
"""

#Task1
import json
user_profile={
    "name":"priya",
    "age":25,
    "email":"priya@example.com",
    "is_active":True,
    "skills":["python","sql","data analysis"]
}
json_data=json.dumps(user_profile,indent=4)
print(json_data)

#Task2
api_response='{"status": "success", "data": {"user_id": 101, "username": "alex99", "score": 87.5}}'
data=json.loads(api_response)
username=data["data"]["username"]
score=data["data"]["score"]
print(username)
print(score)
print(f"User{username}Scored{score}points")

#Task3
user= {
  "name": "Priya",
  "address": {
    "city": "Bengaluru",
    "state": "Karnataka",
    "zip": "560001"
  }
}
city=user["address"]["city"]
zip_code=user["address"]["zip"]
print(city)
print(zip_code)
user["address"]["country"]="india"
print(json.dumps(user,indent=4))